### ISSUE TITLE
Battery showing always '100 full' when plugged in is back

### ISSUE THREAD

**Issue by melonlm** [nowrep/dualsensectl#13]
Hi!

As in the title.

Had a quick look in the kernel driver: https://elixir.bootlin.com/linux/latest/source/drivers/hid/hid-playstation.c#L1181 , 
and it seems that `charging_status` decoding is now slightly wrong in dualsensectl.

Swapping around lines 434 and 438 in main.c seems to help ;)

**Comment by MartinVonReichenberg** [comment]
I didn't notice that, either via USB cable or via Bluetooth . . .

**Comment by nowrep** [comment]
Can you confirm this patch fixes it?

```diff
diff --git a/main.c b/main.c
index dfe9f3a..d105439 100644
--- a/main.c
+++ b/main.c
@@ -432,13 +432,13 @@ static int command_battery(struct dualsense *ds)
         battery_status = "discharging";
         break;
     case 0x1:
-        battery_capacity = 100;
-        battery_status = "full";
-        break;
-    case 0x2:
         battery_capacity = min(battery_data * 10 + 5, 100);
         battery_status = "charging";
         break;
+    case 0x2:
+        battery_capacity = 100;
+        battery_status = "full";
+        break;
     case 0xa: /* voltage or temperature out of range */
     case 0xb: /* temperature error */
         battery_capacity = 0;
```

**Comment by melonlm** [comment]
Confirmed. The change below fixes the issue for me.

> Can you confirm this patch fixes it?
> 
> ```diff
> diff --git a/main.c b/main.c
> index dfe9f3a..d105439 100644
> --- a/main.c
> +++ b/main.c
> @@ -432,13 +432,13 @@ static int command_battery(struct dualsense *ds)
>          battery_status = "discharging";
>          break;
>      case 0x1:
> -        battery_capacity = 100;
> -        battery_status = "full";
> -        break;
> -    case 0x2:
>          battery_capacity = min(battery_data * 10 + 5, 100);
>          battery_status = "charging";
>          break;
> +    case 0x2:
> +        battery_capacity = 100;
> +        battery_status = "full";
> +        break;
>      case 0xa: /* voltage or temperature out of range */
>      case 0xb: /* temperature error */
>          battery_capacity = 0;
> ```
