### ISSUE TITLE
ask for a source (no issue)

### ISSUE THREAD

**Issue by nonobody15** [nowrep/dualsensectl#15]
Hi, 
I'm not sure if this is the right channel, please correct me if not. 
I am trying to port the functions you provided (Lightbar controll, LED controll, ...) for the ESP32, based on the Arduino library (https://github.com/rodneybakiskan/ps5-esp32). 
So I would like to ask where you got your information for the PS5 Linux tool, regarding the structure of the ble package. In particular, I am interested in the structure of the package to control the controller (LEDs, Rumbl motor,...).

I would be very happy about a hint or a source.

**Comment by nowrep** [comment]
Linux playstation driver: [drivers/hid/hid-playstation.c](https://github.com/torvalds/linux/blob/master/drivers/hid/hid-playstation.c)
