### ISSUE TITLE
[Feature Request] Adaptive trigger support

### ISSUE THREAD

**Issue by azuwis** [nowrep/dualsensectl#18]
Currently I'm using https://github.com/Etaash-mathamsetty/trigger-control/ to control the adaptive trigger of the DualSense controller, which is GUI app.

I'd like to use command line to automate the process, e.g. apply preset when controller is connected using udev.

It would be very useful if dualsensectl can support config adaptive trigger, make it the most feature rich command line tool for DualSense.

**Comment by shadowwa** [comment]
You can try the fork I've done some months ago https://github.com/shadowwa/dualsensectl .

If I find time, I should update it and create a PR.

**Comment by nowrep** [comment]
Added now in 0.4 release
