### ISSUE TITLE
Battery percentage always shown as "100" if plugged in

### ISSUE THREAD

**Issue by Northcode** [nowrep/dualsensectl#2]
When plugging in the controller via usb, `dualsensectl battery` shows 100.
disconnecting the usb and using bluetooth directly after then shows actual battery.

Example where I first tested on bluetooth and then plugged in usb:
![image](https://user-images.githubusercontent.com/2746049/154849057-a4506fd2-384c-4895-90d0-01d6b1d22079.png)

I couldn't find any logs so let me know if theres a debug mode or something I can activate to provide more info.

**Comment by nowrep** [comment]
I'm aware of this, but the code was taken from the linux kernel module https://github.com/torvalds/linux/blob/6e8e752f705c2713005a3182c8444ef7b54f10aa/drivers/hid/hid-playstation.c#L1149 and it's the same :shrug: 

I'm not sure if even PS5 shows the battery value when plugged in.

**Comment by MartinVonReichenberg** [comment]
Another online viewer for code is [here](https://elixir.bootlin.com/linux/latest/source/drivers/hid/hid-playstation.c) . . .
