### ISSUE TITLE
Documentation with working examples

### ISSUE THREAD

**Issue by theflyingape** [nowrep/dualsensectl#21]
First, **thank you** for this incredibly useful tool!

Please consider appending working examples off the README page for each `command` crafted for this useful tool. While the mainstream ones are easily discernible with value-checking, there is need especially for:

- `attenuation`
- `trigger` with each embedded vibration macro
- `monitor`

Bash completion and UDEV rule example scripts would be a nice add-on too.

**Comment by shadowwa** [comment]
I can give you a list of recipes I have used in my tests that can be added to the readme on maybe better on a wiki

# Speaker and Volume

## setting the sound to the gamepad speaker and increasing the volume to the max
```
dualsensectl speaker internal
dualsensectl volume 255
```

the volume seems stronger on the jack device:
at 50 I hear the sound and at 200 I need to remove the headset from my ears to not be hurt
but with the internal speaker I need to set at least 150 to be able to hear something

## setting the sound to the gamepad jack device in stereo
```
dualsensectl speaker headphone
```

## setting the sound to the gamepad jack device to the left channel
```
dualsensectl speaker monoheadphone
```

## setting the sound to the gamepad speaker and jack device (left channel go to the jack device, right one to the gamepad speaker)
```
dualsensectl speaker both
```

# Attenuation

## almost not vibrate when receiving rumble command (attenuate the maximum)
```
dualsensectl attenuation 7 0
```

## vibrate the maximum (do not attenuate)
```
dualsensectl attenuation 0 0
```

I remember that modifying the second parameter had an impact on the vibration of the trigger but maybe that was changed by a firmware upgrade but now it seems to have no effect


# trigger

the **position** parameter, as well as **start** and **stop** reflect how much the trigger is pressed
 - position 0 is trigger just begin to be pressed
 - position 9 is trigger completely pressed

depending on the **mode** you choose, position limits can varie

the strength parameter is the amount of resistance the trigger will oppose as you press
 - strength 1 : trigger oppose almost no resistance
 - strength 8 : trigger oppose the maximum resistance

## give a slight constant resistance to the right trigger from the beginning of the course
```
dualsensectl trigger right feedback 0 1
```

## give a slight constant resistance to the left trigger from the end of the course
```
dualsensectl trigger left feedback 9 1
```

## give a strong constant resistance to both triggers midway
```
dualsensectl trigger both feedback 5 8
```

## strongly resist at the beginning of the course and stop resisting almost immediately
```
dualsensectl trigger both weapon 2 3 8
```

## strongly resist at the beginning of the course and stop resisting at the end of the course
```
dualsensectl trigger both weapon 2 8 8
```

## slightly resist at the beginning of the course and stop resisting midway
```
dualsensectl trigger both weapon 2 5 1
```

## strongly resist at the beginning of the course and stop resisting at the end of the course then when the trigger is release snap back strongly
```
dualsensectl trigger both bow 1 8 8 8
```

## strongly resist at the beginning of the course and stop resisting at the end of the course then when the trigger is release snap back slightly
```
dualsensectl trigger both bow 1 8 8 1
```


## feel a heartbeat whenever the trigger is pressed
```
dualsensectl trigger both galloping 0 9 1 3 1
```

## more like a horse whenever the trigger is pressed
```
dualsensectl trigger both galloping 0 9 2 3 2
```

## vibrate strongly, slowly calm down then slowly go back to vibrating strongly during almost all the course of the trigger
```
dualsensectl trigger both machine 1 9 7 0 100 100
```

## machine gun during almost all the course of the trigger
```
dualsensectl trigger both machine 1 9 7 7 9 1
```

## burst of machine gun during almost all the course of the trigger
```
dualsensectl trigger both machine 1 9 7 0 18 12
```

## slightly vibrate a 60 Hz from the the beginning of the course
```
dualsensectl trigger both vibration 1 1 60
```

## strongly vibrate a 120 Hz from the the beginning of the course
```
dualsensectl trigger both vibration 1 8 120
```

## you are not holding a gamepad anymore but a giant clock
```
dualsensectl trigger both vibration 1 8 1
```

## resistance at the beginning of the course, stopping immediately then resistance again mid course also stopping immediately (double tap in case of zombies)
```
dualsensectl trigger both feedback-raw 1 2 8 0 0 1 2 8 0 0
```

## as if the trigger was rusty
```
dualsensectl trigger both feedback-raw 0 8 0 8 0 8 0 8 0 8
```

## the more you press, the harder is the resistance, until the last position
```
dualsensectl trigger both feedback-raw 0 1 2 3 4 5 6 7 8 0
```

## the more you press, the more you feel the vibration as 100Hz
```
dualsensectl trigger both vibration-raw 0 1 2 3 4 5 6 7 8 8 100
```

## you feel the vibration at 25Hz only when the trigger is around midway
```
dualsensectl trigger both vibration-raw 0 0 0 0 5 8 5 0 0 0 25
```

## no more vibrations or resistances
```
dualsensectl trigger both off
```

**Comment by nowrep** [comment]
@shadowwa I gave you access to wiki, you can add it there. Thanks!

**Comment by shadowwa** [comment]
Thanks, I'll do that
