### ISSUE TITLE
Fails to build

### ISSUE THREAD

**Issue by WiseFerret** [nowrep/dualsensectl#3]
Under ubuntu 22.04, with libdbus-1-dev, libhidapi-hidraw0 and libhidapy-dev packages installed, I get the following uponn "make":

`$ make
gcc -o dualsensectl -DDUALSENSECTL_VERSION=\"0.1\" -Wall -Wextra -pedantic -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/hidapi -O2 -s -DNDEBUG -ldbus-1 -lhidapi-hidraw main.c
/usr/bin/ld: /tmp/ccGRR8hJ.o: in function `dualsense_send_output_report':
main.c:(.text+0xa0): undefined reference to `hid_write'
/usr/bin/ld: main.c:(.text+0xee): undefined reference to `hid_error'
/usr/bin/ld: /tmp/ccGRR8hJ.o: in function `dualsense_bt_disconnect.isra.0':
main.c:(.text+0x226): undefined reference to `dbus_error_init'
/usr/bin/ld: main.c:(.text+0x233): undefined reference to `dbus_bus_get'
/usr/bin/ld: main.c:(.text+0x240): undefined reference to `dbus_error_is_set'
/usr/bin/ld: main.c:(.text+0x269): undefined reference to `dbus_message_new_method_call'
/usr/bin/ld: main.c:(.text+0x284): undefined reference to `dbus_connection_send_with_reply_and_block'
/usr/bin/ld: main.c:(.text+0x291): undefined reference to `dbus_message_unref'
/usr/bin/ld: main.c:(.text+0x299): undefined reference to `dbus_error_is_set'
/usr/bin/ld: main.c:(.text+0x2b6): undefined reference to `dbus_message_iter_init'
/usr/bin/ld: main.c:(.text+0x2be): undefined reference to `dbus_message_iter_get_element_count'
/usr/bin/ld: main.c:(.text+0x2d8): undefined reference to `dbus_message_iter_recurse'
/usr/bin/ld: main.c:(.text+0x316): undefined reference to `dbus_message_iter_next'
/usr/bin/ld: main.c:(.text+0x339): undefined reference to `dbus_message_iter_recurse'
/usr/bin/ld: main.c:(.text+0x346): undefined reference to `dbus_message_iter_get_basic'
/usr/bin/ld: main.c:(.text+0x34e): undefined reference to `dbus_message_iter_next'
/usr/bin/ld: main.c:(.text+0x356): undefined reference to `dbus_message_iter_get_element_count'
/usr/bin/ld: main.c:(.text+0x363): undefined reference to `dbus_message_iter_recurse'
/usr/bin/ld: main.c:(.text+0x3a6): undefined reference to `dbus_message_iter_recurse'
/usr/bin/ld: main.c:(.text+0x3b6): undefined reference to `dbus_message_iter_get_basic'
/usr/bin/ld: main.c:(.text+0x3d7): undefined reference to `dbus_message_iter_next'
/usr/bin/ld: main.c:(.text+0x45c): undefined reference to `dbus_message_iter_next'
/usr/bin/ld: main.c:(.text+0x464): undefined reference to `dbus_message_iter_get_element_count'
/usr/bin/ld: main.c:(.text+0x473): undefined reference to `dbus_message_iter_recurse'
/usr/bin/ld: main.c:(.text+0x4c3): undefined reference to `dbus_message_iter_next'
/usr/bin/ld: main.c:(.text+0x4d3): undefined reference to `dbus_message_iter_recurse'
/usr/bin/ld: main.c:(.text+0x4de): undefined reference to `dbus_message_iter_get_basic'
/usr/bin/ld: main.c:(.text+0x509): undefined reference to `dbus_message_iter_next'
/usr/bin/ld: main.c:(.text+0x514): undefined reference to `dbus_message_iter_recurse'
/usr/bin/ld: main.c:(.text+0x524): undefined reference to `dbus_message_iter_get_basic'
/usr/bin/ld: main.c:(.text+0x52c): undefined reference to `dbus_message_iter_next'
/usr/bin/ld: main.c:(.text+0x576): undefined reference to `dbus_message_iter_next'
/usr/bin/ld: main.c:(.text+0x59e): undefined reference to `dbus_message_iter_next'
/usr/bin/ld: main.c:(.text+0x5c4): undefined reference to `dbus_message_unref'
/usr/bin/ld: main.c:(.text+0x5e1): undefined reference to `dbus_message_new_method_call'
/usr/bin/ld: main.c:(.text+0x5fc): undefined reference to `dbus_connection_send_with_reply_and_block'
/usr/bin/ld: main.c:(.text+0x607): undefined reference to `dbus_message_unref'
/usr/bin/ld: main.c:(.text+0x60f): undefined reference to `dbus_error_is_set'
/usr/bin/ld: main.c:(.text+0x625): undefined reference to `dbus_message_unref'
/usr/bin/ld: main.c:(.text+0x62f): undefined reference to `dbus_connection_unref'
/usr/bin/ld: main.c:(.text+0x64c): undefined reference to `dbus_message_iter_next'
/usr/bin/ld: main.c:(.text+0x657): undefined reference to `dbus_message_iter_recurse'
/usr/bin/ld: main.c:(.text+0x664): undefined reference to `dbus_message_iter_get_basic'
/usr/bin/ld: main.c:(.text+0x674): undefined reference to `dbus_message_iter_next'
/usr/bin/ld: main.c:(.text+0x6ae): undefined reference to `dbus_message_unref'
/usr/bin/ld: main.c:(.text+0x6c3): undefined reference to `dbus_message_unref'
/usr/bin/ld: /tmp/ccGRR8hJ.o: in function `main':
main.c:(.text.startup+0xfc): undefined reference to `hid_open'
/usr/bin/ld: main.c:(.text.startup+0x134): undefined reference to `hid_get_feature_report'
/usr/bin/ld: main.c:(.text.startup+0x324): undefined reference to `hid_error'
collect2: error: ld returned 1 exit status
make: *** [Makefile:20: all] Error 1
`

**Comment by nowrep** [comment]
Same as #1, please build from master.
