### ISSUE TITLE
Cannot change speaker STATE

### ISSUE THREAD

**Issue by MrNessuno** [nowrep/dualsensectl#39]
![immagine](https://github.com/user-attachments/assets/7055fec1-a182-46f9-ad13-0f3da22303f8)

When I try to change speaker state i get invalid argument as output. Am I doing something wrong?

**Comment by shadowwa** [comment]
_STATE_ is the placeholder that should be replaced by wanted state.
the command lines should be
```bash
$ dualsensectl speaker both
$ dualsensectl speaker headphone
$ dualsensectl speaker internal
```
