### ISSUE TITLE
Can you auto apply changed settings after reconnecting?

### ISSUE THREAD

**Issue by imsl0wer** [nowrep/dualsensectl#7]
title

**Comment by class101** [comment]
Hey @imsl0wer 

Maybe you will find the following useful, which consists in starting and stopping an application named solaar, when my keyboard connects and disconnects

This is using a udev rule which will call a user service which will execute the desired command

`etc/udev/rules.d/99-solaar.rules`
```bash
ACTION=="add", ATTR{id/vendor}=="046d", ATTR{id/product}=="b369", ENV{SYSTEMD_USER_WANTS}+="solaar.service", TAG+="systemd"
ACTION=="remove", ATTR{id/vendor}=="046d", ATTR{id/product}=="b369", RUN+="killall -9 solaar"
```

`/home/deck/.config/systemd/user/solaar.service`
```bash
[Unit]
Description=solaar udev service

[Service]
Environment="DISPLAY=:0"
Type=oneshot
RemainAfterExit=no
ExecStart=/home/deck/script/run-solaar.sh

[Install]
WantedBy=graphical.target
```
